name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Generate Prisma client
      run: yarn prisma:generate

    - name: Run database migrations
      run: yarn prisma:migrate

    - name: Seed database
      run: yarn prisma:seed

    - name: Lint backend
      run: yarn workspace backend lint

    - name: Type check backend
      run: yarn workspace backend typecheck

    - name: Lint frontend
      run: yarn workspace frontend lint

    - name: Type check frontend
      run: yarn workspace frontend typecheck

    - name: Run backend tests
      run: yarn workspace backend test

    - name: Run frontend tests
      run: yarn workspace frontend test

    - name: Build backend
      run: yarn workspace backend build

    - name: Build frontend
      run: yarn workspace frontend build

    - name: Run E2E tests
      run: yarn test:e2e
      if: matrix.node-version == '20.x'


